//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace SearchFood.SearchFoodServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchFoodServiceReference.ISearchFoodService")]
    public interface ISearchFoodService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetCategories", ReplyAction="http://tempuri.org/ISearchFoodService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<string> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetCategorie", ReplyAction="http://tempuri.org/ISearchFoodService/GetCategorieResponse")]
        System.Threading.Tasks.Task<int> GetCategorieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddCategories", ReplyAction="http://tempuri.org/ISearchFoodService/AddCategoriesResponse")]
        System.Threading.Tasks.Task AddCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteCategories", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteCategoriesResponse")]
        System.Threading.Tasks.Task DeleteCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateCategories", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateCategoriesResponse")]
        System.Threading.Tasks.Task UpdateCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetCommentaires", ReplyAction="http://tempuri.org/ISearchFoodService/GetCommentairesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<int>> GetCommentairesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetCommentaire", ReplyAction="http://tempuri.org/ISearchFoodService/GetCommentaireResponse")]
        System.Threading.Tasks.Task<int> GetCommentaireAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddCommentaires", ReplyAction="http://tempuri.org/ISearchFoodService/AddCommentairesResponse")]
        System.Threading.Tasks.Task AddCommentairesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteCommentaires", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteCommentairesResponse")]
        System.Threading.Tasks.Task DeleteCommentairesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateCommentaires", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateCommentairesResponse")]
        System.Threading.Tasks.Task UpdateCommentairesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetHistorique", ReplyAction="http://tempuri.org/ISearchFoodService/GetHistoriqueResponse")]
        System.Threading.Tasks.Task<int> GetHistoriqueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddHistorique", ReplyAction="http://tempuri.org/ISearchFoodService/AddHistoriqueResponse")]
        System.Threading.Tasks.Task AddHistoriqueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteHistorique", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteHistoriqueResponse")]
        System.Threading.Tasks.Task DeleteHistoriqueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateHistorique", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateHistoriqueResponse")]
        System.Threading.Tasks.Task UpdateHistoriqueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetNotes", ReplyAction="http://tempuri.org/ISearchFoodService/GetNotesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<int>> GetNotesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetNote", ReplyAction="http://tempuri.org/ISearchFoodService/GetNoteResponse")]
        System.Threading.Tasks.Task<int> GetNoteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddNotes", ReplyAction="http://tempuri.org/ISearchFoodService/AddNotesResponse")]
        System.Threading.Tasks.Task AddNotesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteNotes", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteNotesResponse")]
        System.Threading.Tasks.Task DeleteNotesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateNotes", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateNotesResponse")]
        System.Threading.Tasks.Task UpdateNotesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetRestaurants", ReplyAction="http://tempuri.org/ISearchFoodService/GetRestaurantsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<int>> GetRestaurantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetRestaurant", ReplyAction="http://tempuri.org/ISearchFoodService/GetRestaurantResponse")]
        System.Threading.Tasks.Task<int> GetRestaurantAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddRestaurants", ReplyAction="http://tempuri.org/ISearchFoodService/AddRestaurantsResponse")]
        System.Threading.Tasks.Task AddRestaurantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteRestaurants", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteRestaurantsResponse")]
        System.Threading.Tasks.Task DeleteRestaurantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateRestaurants", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateRestaurantsResponse")]
        System.Threading.Tasks.Task UpdateRestaurantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetTypesCuisine", ReplyAction="http://tempuri.org/ISearchFoodService/GetTypesCuisineResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<int>> GetTypesCuisineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetTypeCuisine", ReplyAction="http://tempuri.org/ISearchFoodService/GetTypeCuisineResponse")]
        System.Threading.Tasks.Task<int> GetTypeCuisineAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddTypesCuisine", ReplyAction="http://tempuri.org/ISearchFoodService/AddTypesCuisineResponse")]
        System.Threading.Tasks.Task AddTypesCuisineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteTypesCuisine", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteTypesCuisineResponse")]
        System.Threading.Tasks.Task DeleteTypesCuisineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateTypesCuisine", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateTypesCuisineResponse")]
        System.Threading.Tasks.Task UpdateTypesCuisineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetUtilisateurs", ReplyAction="http://tempuri.org/ISearchFoodService/GetUtilisateursResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<int>> GetUtilisateursAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetUtilisateur", ReplyAction="http://tempuri.org/ISearchFoodService/GetUtilisateurResponse")]
        System.Threading.Tasks.Task<int> GetUtilisateurAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddUtilisateurs", ReplyAction="http://tempuri.org/ISearchFoodService/AddUtilisateursResponse")]
        System.Threading.Tasks.Task AddUtilisateursAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteUtilisateurs", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteUtilisateursResponse")]
        System.Threading.Tasks.Task DeleteUtilisateursAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateUtilisateurs", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateUtilisateursResponse")]
        System.Threading.Tasks.Task UpdateUtilisateursAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchFoodServiceChannel : SearchFood.SearchFoodServiceReference.ISearchFoodService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchFoodServiceClient : System.ServiceModel.ClientBase<SearchFood.SearchFoodServiceReference.ISearchFoodService>, SearchFood.SearchFoodServiceReference.ISearchFoodService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SearchFoodServiceClient() : 
                base(SearchFoodServiceClient.GetDefaultBinding(), SearchFoodServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISearchFoodService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchFoodServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SearchFoodServiceClient.GetBindingForEndpoint(endpointConfiguration), SearchFoodServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchFoodServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SearchFoodServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchFoodServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SearchFoodServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchFoodServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<string> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCategorieAsync(int id) {
            return base.Channel.GetCategorieAsync(id);
        }
        
        public System.Threading.Tasks.Task AddCategoriesAsync() {
            return base.Channel.AddCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task DeleteCategoriesAsync() {
            return base.Channel.DeleteCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task UpdateCategoriesAsync() {
            return base.Channel.UpdateCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<int>> GetCommentairesAsync() {
            return base.Channel.GetCommentairesAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetCommentaireAsync(int id) {
            return base.Channel.GetCommentaireAsync(id);
        }
        
        public System.Threading.Tasks.Task AddCommentairesAsync() {
            return base.Channel.AddCommentairesAsync();
        }
        
        public System.Threading.Tasks.Task DeleteCommentairesAsync() {
            return base.Channel.DeleteCommentairesAsync();
        }
        
        public System.Threading.Tasks.Task UpdateCommentairesAsync() {
            return base.Channel.UpdateCommentairesAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetHistoriqueAsync() {
            return base.Channel.GetHistoriqueAsync();
        }
        
        public System.Threading.Tasks.Task AddHistoriqueAsync() {
            return base.Channel.AddHistoriqueAsync();
        }
        
        public System.Threading.Tasks.Task DeleteHistoriqueAsync() {
            return base.Channel.DeleteHistoriqueAsync();
        }
        
        public System.Threading.Tasks.Task UpdateHistoriqueAsync() {
            return base.Channel.UpdateHistoriqueAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<int>> GetNotesAsync() {
            return base.Channel.GetNotesAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetNoteAsync(int id) {
            return base.Channel.GetNoteAsync(id);
        }
        
        public System.Threading.Tasks.Task AddNotesAsync() {
            return base.Channel.AddNotesAsync();
        }
        
        public System.Threading.Tasks.Task DeleteNotesAsync() {
            return base.Channel.DeleteNotesAsync();
        }
        
        public System.Threading.Tasks.Task UpdateNotesAsync() {
            return base.Channel.UpdateNotesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<int>> GetRestaurantsAsync() {
            return base.Channel.GetRestaurantsAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetRestaurantAsync(int id) {
            return base.Channel.GetRestaurantAsync(id);
        }
        
        public System.Threading.Tasks.Task AddRestaurantsAsync() {
            return base.Channel.AddRestaurantsAsync();
        }
        
        public System.Threading.Tasks.Task DeleteRestaurantsAsync() {
            return base.Channel.DeleteRestaurantsAsync();
        }
        
        public System.Threading.Tasks.Task UpdateRestaurantsAsync() {
            return base.Channel.UpdateRestaurantsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<int>> GetTypesCuisineAsync() {
            return base.Channel.GetTypesCuisineAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetTypeCuisineAsync(int id) {
            return base.Channel.GetTypeCuisineAsync(id);
        }
        
        public System.Threading.Tasks.Task AddTypesCuisineAsync() {
            return base.Channel.AddTypesCuisineAsync();
        }
        
        public System.Threading.Tasks.Task DeleteTypesCuisineAsync() {
            return base.Channel.DeleteTypesCuisineAsync();
        }
        
        public System.Threading.Tasks.Task UpdateTypesCuisineAsync() {
            return base.Channel.UpdateTypesCuisineAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<int>> GetUtilisateursAsync() {
            return base.Channel.GetUtilisateursAsync();
        }
        
        public System.Threading.Tasks.Task<int> GetUtilisateurAsync(int id) {
            return base.Channel.GetUtilisateurAsync(id);
        }
        
        public System.Threading.Tasks.Task AddUtilisateursAsync() {
            return base.Channel.AddUtilisateursAsync();
        }
        
        public System.Threading.Tasks.Task DeleteUtilisateursAsync() {
            return base.Channel.DeleteUtilisateursAsync();
        }
        
        public System.Threading.Tasks.Task UpdateUtilisateursAsync() {
            return base.Channel.UpdateUtilisateursAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISearchFoodService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISearchFoodService)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:24048/SearchFoodService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return SearchFoodServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISearchFoodService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return SearchFoodServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISearchFoodService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_ISearchFoodService,
        }
    }
}
