//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.21005.1
// 
namespace SearchFood.SearchFoodServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categorie", Namespace="http://schemas.datacontract.org/2004/07/SearchFoodServer")]
    public partial class Categorie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int Id_CategorieField;
        
        private string Nom_CategorieField;
        
        private System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Restaurant> RestaurantField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Categorie {
            get {
                return this.Id_CategorieField;
            }
            set {
                if ((this.Id_CategorieField.Equals(value) != true)) {
                    this.Id_CategorieField = value;
                    this.RaisePropertyChanged("Id_Categorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Categorie {
            get {
                return this.Nom_CategorieField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_CategorieField, value) != true)) {
                    this.Nom_CategorieField = value;
                    this.RaisePropertyChanged("Nom_Categorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Restaurant> Restaurant {
            get {
                return this.RestaurantField;
            }
            set {
                if ((object.ReferenceEquals(this.RestaurantField, value) != true)) {
                    this.RestaurantField = value;
                    this.RaisePropertyChanged("Restaurant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restaurant", Namespace="http://schemas.datacontract.org/2004/07/SearchFoodServer")]
    public partial class Restaurant : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdresseField;
        
        private SearchFood.SearchFoodServiceReference.Categorie CategorieField;
        
        private string Code_PostalField;
        
        private System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Commentaire> CommentaireField;
        
        private System.Nullable<int> Duree_repasField;
        
        private System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Historique> HistoriqueField;
        
        private int Id_CategorieField;
        
        private int Id_RestaurantField;
        
        private int Id_Type_CuisineField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string MailField;
        
        private string NomField;
        
        private System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Note> NoteField;
        
        private System.Nullable<double> PrixField;
        
        private string Site_WebField;
        
        private string TelephoneField;
        
        private SearchFood.SearchFoodServiceReference.Type_Cuisine Type_CuisineField;
        
        private string VilleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchFood.SearchFoodServiceReference.Categorie Categorie {
            get {
                return this.CategorieField;
            }
            set {
                if ((object.ReferenceEquals(this.CategorieField, value) != true)) {
                    this.CategorieField = value;
                    this.RaisePropertyChanged("Categorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code_Postal {
            get {
                return this.Code_PostalField;
            }
            set {
                if ((object.ReferenceEquals(this.Code_PostalField, value) != true)) {
                    this.Code_PostalField = value;
                    this.RaisePropertyChanged("Code_Postal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Commentaire> Commentaire {
            get {
                return this.CommentaireField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentaireField, value) != true)) {
                    this.CommentaireField = value;
                    this.RaisePropertyChanged("Commentaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Duree_repas {
            get {
                return this.Duree_repasField;
            }
            set {
                if ((this.Duree_repasField.Equals(value) != true)) {
                    this.Duree_repasField = value;
                    this.RaisePropertyChanged("Duree_repas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Historique> Historique {
            get {
                return this.HistoriqueField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoriqueField, value) != true)) {
                    this.HistoriqueField = value;
                    this.RaisePropertyChanged("Historique");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Categorie {
            get {
                return this.Id_CategorieField;
            }
            set {
                if ((this.Id_CategorieField.Equals(value) != true)) {
                    this.Id_CategorieField = value;
                    this.RaisePropertyChanged("Id_Categorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Restaurant {
            get {
                return this.Id_RestaurantField;
            }
            set {
                if ((this.Id_RestaurantField.Equals(value) != true)) {
                    this.Id_RestaurantField = value;
                    this.RaisePropertyChanged("Id_Restaurant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Type_Cuisine {
            get {
                return this.Id_Type_CuisineField;
            }
            set {
                if ((this.Id_Type_CuisineField.Equals(value) != true)) {
                    this.Id_Type_CuisineField = value;
                    this.RaisePropertyChanged("Id_Type_Cuisine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Note> Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Prix {
            get {
                return this.PrixField;
            }
            set {
                if ((this.PrixField.Equals(value) != true)) {
                    this.PrixField = value;
                    this.RaisePropertyChanged("Prix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Site_Web {
            get {
                return this.Site_WebField;
            }
            set {
                if ((object.ReferenceEquals(this.Site_WebField, value) != true)) {
                    this.Site_WebField = value;
                    this.RaisePropertyChanged("Site_Web");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchFood.SearchFoodServiceReference.Type_Cuisine Type_Cuisine {
            get {
                return this.Type_CuisineField;
            }
            set {
                if ((object.ReferenceEquals(this.Type_CuisineField, value) != true)) {
                    this.Type_CuisineField = value;
                    this.RaisePropertyChanged("Type_Cuisine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Type_Cuisine", Namespace="http://schemas.datacontract.org/2004/07/SearchFoodServer")]
    public partial class Type_Cuisine : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int Id_Type_CuisineField;
        
        private System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Restaurant> RestaurantField;
        
        private string Type_Cuisine1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Type_Cuisine {
            get {
                return this.Id_Type_CuisineField;
            }
            set {
                if ((this.Id_Type_CuisineField.Equals(value) != true)) {
                    this.Id_Type_CuisineField = value;
                    this.RaisePropertyChanged("Id_Type_Cuisine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Restaurant> Restaurant {
            get {
                return this.RestaurantField;
            }
            set {
                if ((object.ReferenceEquals(this.RestaurantField, value) != true)) {
                    this.RestaurantField = value;
                    this.RaisePropertyChanged("Restaurant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type_Cuisine1 {
            get {
                return this.Type_Cuisine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Type_Cuisine1Field, value) != true)) {
                    this.Type_Cuisine1Field = value;
                    this.RaisePropertyChanged("Type_Cuisine1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commentaire", Namespace="http://schemas.datacontract.org/2004/07/SearchFoodServer")]
    public partial class Commentaire : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string Commentaire1Field;
        
        private int Id_CommentaireField;
        
        private System.Nullable<int> Id_RestaurantField;
        
        private System.Nullable<int> Id_UtilisateurField;
        
        private SearchFood.SearchFoodServiceReference.Restaurant RestaurantField;
        
        private SearchFood.SearchFoodServiceReference.Utilisateur UtilisateurField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commentaire1 {
            get {
                return this.Commentaire1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Commentaire1Field, value) != true)) {
                    this.Commentaire1Field = value;
                    this.RaisePropertyChanged("Commentaire1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Commentaire {
            get {
                return this.Id_CommentaireField;
            }
            set {
                if ((this.Id_CommentaireField.Equals(value) != true)) {
                    this.Id_CommentaireField = value;
                    this.RaisePropertyChanged("Id_Commentaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_Restaurant {
            get {
                return this.Id_RestaurantField;
            }
            set {
                if ((this.Id_RestaurantField.Equals(value) != true)) {
                    this.Id_RestaurantField = value;
                    this.RaisePropertyChanged("Id_Restaurant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_Utilisateur {
            get {
                return this.Id_UtilisateurField;
            }
            set {
                if ((this.Id_UtilisateurField.Equals(value) != true)) {
                    this.Id_UtilisateurField = value;
                    this.RaisePropertyChanged("Id_Utilisateur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchFood.SearchFoodServiceReference.Restaurant Restaurant {
            get {
                return this.RestaurantField;
            }
            set {
                if ((object.ReferenceEquals(this.RestaurantField, value) != true)) {
                    this.RestaurantField = value;
                    this.RaisePropertyChanged("Restaurant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchFood.SearchFoodServiceReference.Utilisateur Utilisateur {
            get {
                return this.UtilisateurField;
            }
            set {
                if ((object.ReferenceEquals(this.UtilisateurField, value) != true)) {
                    this.UtilisateurField = value;
                    this.RaisePropertyChanged("Utilisateur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Historique", Namespace="http://schemas.datacontract.org/2004/07/SearchFoodServer")]
    public partial class Historique : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime DateField;
        
        private int Id_RestaurantField;
        
        private int Id_UtilisateurField;
        
        private SearchFood.SearchFoodServiceReference.Restaurant RestaurantField;
        
        private SearchFood.SearchFoodServiceReference.Utilisateur UtilisateurField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Restaurant {
            get {
                return this.Id_RestaurantField;
            }
            set {
                if ((this.Id_RestaurantField.Equals(value) != true)) {
                    this.Id_RestaurantField = value;
                    this.RaisePropertyChanged("Id_Restaurant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Utilisateur {
            get {
                return this.Id_UtilisateurField;
            }
            set {
                if ((this.Id_UtilisateurField.Equals(value) != true)) {
                    this.Id_UtilisateurField = value;
                    this.RaisePropertyChanged("Id_Utilisateur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchFood.SearchFoodServiceReference.Restaurant Restaurant {
            get {
                return this.RestaurantField;
            }
            set {
                if ((object.ReferenceEquals(this.RestaurantField, value) != true)) {
                    this.RestaurantField = value;
                    this.RaisePropertyChanged("Restaurant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchFood.SearchFoodServiceReference.Utilisateur Utilisateur {
            get {
                return this.UtilisateurField;
            }
            set {
                if ((object.ReferenceEquals(this.UtilisateurField, value) != true)) {
                    this.UtilisateurField = value;
                    this.RaisePropertyChanged("Utilisateur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Note", Namespace="http://schemas.datacontract.org/2004/07/SearchFoodServer")]
    public partial class Note : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int Id_RestaurantField;
        
        private int Id_UtilisateurField;
        
        private double Note1Field;
        
        private SearchFood.SearchFoodServiceReference.Restaurant RestaurantField;
        
        private SearchFood.SearchFoodServiceReference.Utilisateur UtilisateurField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Restaurant {
            get {
                return this.Id_RestaurantField;
            }
            set {
                if ((this.Id_RestaurantField.Equals(value) != true)) {
                    this.Id_RestaurantField = value;
                    this.RaisePropertyChanged("Id_Restaurant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Utilisateur {
            get {
                return this.Id_UtilisateurField;
            }
            set {
                if ((this.Id_UtilisateurField.Equals(value) != true)) {
                    this.Id_UtilisateurField = value;
                    this.RaisePropertyChanged("Id_Utilisateur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Note1 {
            get {
                return this.Note1Field;
            }
            set {
                if ((this.Note1Field.Equals(value) != true)) {
                    this.Note1Field = value;
                    this.RaisePropertyChanged("Note1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchFood.SearchFoodServiceReference.Restaurant Restaurant {
            get {
                return this.RestaurantField;
            }
            set {
                if ((object.ReferenceEquals(this.RestaurantField, value) != true)) {
                    this.RestaurantField = value;
                    this.RaisePropertyChanged("Restaurant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SearchFood.SearchFoodServiceReference.Utilisateur Utilisateur {
            get {
                return this.UtilisateurField;
            }
            set {
                if ((object.ReferenceEquals(this.UtilisateurField, value) != true)) {
                    this.UtilisateurField = value;
                    this.RaisePropertyChanged("Utilisateur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utilisateur", Namespace="http://schemas.datacontract.org/2004/07/SearchFoodServer")]
    public partial class Utilisateur : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdresseField;
        
        private string Code_PostalField;
        
        private System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Commentaire> CommentaireField;
        
        private System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Historique> HistoriqueField;
        
        private int Id_UtilisateurField;
        
        private string MailField;
        
        private string NomField;
        
        private System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Note> NoteField;
        
        private string PasswordField;
        
        private string PrenomField;
        
        private string PseudonymeField;
        
        private string TelephoneField;
        
        private string VilleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code_Postal {
            get {
                return this.Code_PostalField;
            }
            set {
                if ((object.ReferenceEquals(this.Code_PostalField, value) != true)) {
                    this.Code_PostalField = value;
                    this.RaisePropertyChanged("Code_Postal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Commentaire> Commentaire {
            get {
                return this.CommentaireField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentaireField, value) != true)) {
                    this.CommentaireField = value;
                    this.RaisePropertyChanged("Commentaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Historique> Historique {
            get {
                return this.HistoriqueField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoriqueField, value) != true)) {
                    this.HistoriqueField = value;
                    this.RaisePropertyChanged("Historique");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Utilisateur {
            get {
                return this.Id_UtilisateurField;
            }
            set {
                if ((this.Id_UtilisateurField.Equals(value) != true)) {
                    this.Id_UtilisateurField = value;
                    this.RaisePropertyChanged("Id_Utilisateur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Note> Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pseudonyme {
            get {
                return this.PseudonymeField;
            }
            set {
                if ((object.ReferenceEquals(this.PseudonymeField, value) != true)) {
                    this.PseudonymeField = value;
                    this.RaisePropertyChanged("Pseudonyme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchFoodServiceReference.ISearchFoodService")]
    public interface ISearchFoodService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetCategories", ReplyAction="http://tempuri.org/ISearchFoodService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Categorie>> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetCategorie", ReplyAction="http://tempuri.org/ISearchFoodService/GetCategorieResponse")]
        System.Threading.Tasks.Task<SearchFood.SearchFoodServiceReference.Categorie> GetCategorieAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddCategories", ReplyAction="http://tempuri.org/ISearchFoodService/AddCategoriesResponse")]
        System.Threading.Tasks.Task AddCategoriesAsync(SearchFood.SearchFoodServiceReference.Categorie c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteCategories", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteCategoriesResponse")]
        System.Threading.Tasks.Task DeleteCategoriesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateCategories", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateCategoriesResponse")]
        System.Threading.Tasks.Task UpdateCategoriesAsync(SearchFood.SearchFoodServiceReference.Categorie c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetCommentaires", ReplyAction="http://tempuri.org/ISearchFoodService/GetCommentairesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Commentaire>> GetCommentairesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetCommentaire", ReplyAction="http://tempuri.org/ISearchFoodService/GetCommentaireResponse")]
        System.Threading.Tasks.Task<SearchFood.SearchFoodServiceReference.Commentaire> GetCommentaireAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddCommentaires", ReplyAction="http://tempuri.org/ISearchFoodService/AddCommentairesResponse")]
        System.Threading.Tasks.Task AddCommentairesAsync(SearchFood.SearchFoodServiceReference.Commentaire c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteCommentaires", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteCommentairesResponse")]
        System.Threading.Tasks.Task DeleteCommentairesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateCommentaires", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateCommentairesResponse")]
        System.Threading.Tasks.Task UpdateCommentairesAsync(SearchFood.SearchFoodServiceReference.Commentaire c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetHistoriques", ReplyAction="http://tempuri.org/ISearchFoodService/GetHistoriquesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Historique>> GetHistoriquesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetHistoriqueByUser", ReplyAction="http://tempuri.org/ISearchFoodService/GetHistoriqueByUserResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Historique>> GetHistoriqueByUserAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddHistorique", ReplyAction="http://tempuri.org/ISearchFoodService/AddHistoriqueResponse")]
        System.Threading.Tasks.Task AddHistoriqueAsync(SearchFood.SearchFoodServiceReference.Historique h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteHistorique", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteHistoriqueResponse")]
        System.Threading.Tasks.Task DeleteHistoriqueAsync(SearchFood.SearchFoodServiceReference.Historique h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateHistorique", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateHistoriqueResponse")]
        System.Threading.Tasks.Task UpdateHistoriqueAsync(SearchFood.SearchFoodServiceReference.Historique h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetNotes", ReplyAction="http://tempuri.org/ISearchFoodService/GetNotesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Note>> GetNotesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetNoteByRestaurant", ReplyAction="http://tempuri.org/ISearchFoodService/GetNoteByRestaurantResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Note>> GetNoteByRestaurantAsync(int idRestaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetNoteByUser", ReplyAction="http://tempuri.org/ISearchFoodService/GetNoteByUserResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Note>> GetNoteByUserAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddNotes", ReplyAction="http://tempuri.org/ISearchFoodService/AddNotesResponse")]
        System.Threading.Tasks.Task AddNotesAsync(SearchFood.SearchFoodServiceReference.Note n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteNotes", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteNotesResponse")]
        System.Threading.Tasks.Task DeleteNotesAsync(SearchFood.SearchFoodServiceReference.Note n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateNotes", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateNotesResponse")]
        System.Threading.Tasks.Task UpdateNotesAsync(SearchFood.SearchFoodServiceReference.Note n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetRestaurants", ReplyAction="http://tempuri.org/ISearchFoodService/GetRestaurantsResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Restaurant>> GetRestaurantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetRestaurant", ReplyAction="http://tempuri.org/ISearchFoodService/GetRestaurantResponse")]
        System.Threading.Tasks.Task<SearchFood.SearchFoodServiceReference.Restaurant> GetRestaurantAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddRestaurants", ReplyAction="http://tempuri.org/ISearchFoodService/AddRestaurantsResponse")]
        System.Threading.Tasks.Task AddRestaurantsAsync(SearchFood.SearchFoodServiceReference.Restaurant r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteRestaurants", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteRestaurantsResponse")]
        System.Threading.Tasks.Task DeleteRestaurantsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateRestaurants", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateRestaurantsResponse")]
        System.Threading.Tasks.Task UpdateRestaurantsAsync(SearchFood.SearchFoodServiceReference.Restaurant r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetTypesCuisine", ReplyAction="http://tempuri.org/ISearchFoodService/GetTypesCuisineResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Type_Cuisine>> GetTypesCuisineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetTypeCuisine", ReplyAction="http://tempuri.org/ISearchFoodService/GetTypeCuisineResponse")]
        System.Threading.Tasks.Task<SearchFood.SearchFoodServiceReference.Type_Cuisine> GetTypeCuisineAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddTypesCuisine", ReplyAction="http://tempuri.org/ISearchFoodService/AddTypesCuisineResponse")]
        System.Threading.Tasks.Task AddTypesCuisineAsync(SearchFood.SearchFoodServiceReference.Type_Cuisine tc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteTypesCuisine", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteTypesCuisineResponse")]
        System.Threading.Tasks.Task DeleteTypesCuisineAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateTypesCuisine", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateTypesCuisineResponse")]
        System.Threading.Tasks.Task UpdateTypesCuisineAsync(SearchFood.SearchFoodServiceReference.Type_Cuisine tc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetUtilisateurs", ReplyAction="http://tempuri.org/ISearchFoodService/GetUtilisateursResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Utilisateur>> GetUtilisateursAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/GetUtilisateur", ReplyAction="http://tempuri.org/ISearchFoodService/GetUtilisateurResponse")]
        System.Threading.Tasks.Task<SearchFood.SearchFoodServiceReference.Utilisateur> GetUtilisateurAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/AddUtilisateurs", ReplyAction="http://tempuri.org/ISearchFoodService/AddUtilisateursResponse")]
        System.Threading.Tasks.Task AddUtilisateursAsync(SearchFood.SearchFoodServiceReference.Utilisateur u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/DeleteUtilisateurs", ReplyAction="http://tempuri.org/ISearchFoodService/DeleteUtilisateursResponse")]
        System.Threading.Tasks.Task DeleteUtilisateursAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchFoodService/UpdateUtilisateurs", ReplyAction="http://tempuri.org/ISearchFoodService/UpdateUtilisateursResponse")]
        System.Threading.Tasks.Task UpdateUtilisateursAsync(SearchFood.SearchFoodServiceReference.Utilisateur u);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchFoodServiceChannel : SearchFood.SearchFoodServiceReference.ISearchFoodService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchFoodServiceClient : System.ServiceModel.ClientBase<SearchFood.SearchFoodServiceReference.ISearchFoodService>, SearchFood.SearchFoodServiceReference.ISearchFoodService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SearchFoodServiceClient() : 
                base(SearchFoodServiceClient.GetDefaultBinding(), SearchFoodServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISearchFoodService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchFoodServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SearchFoodServiceClient.GetBindingForEndpoint(endpointConfiguration), SearchFoodServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchFoodServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SearchFoodServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchFoodServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SearchFoodServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SearchFoodServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Categorie>> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task<SearchFood.SearchFoodServiceReference.Categorie> GetCategorieAsync(int id) {
            return base.Channel.GetCategorieAsync(id);
        }
        
        public System.Threading.Tasks.Task AddCategoriesAsync(SearchFood.SearchFoodServiceReference.Categorie c) {
            return base.Channel.AddCategoriesAsync(c);
        }
        
        public System.Threading.Tasks.Task DeleteCategoriesAsync(int id) {
            return base.Channel.DeleteCategoriesAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateCategoriesAsync(SearchFood.SearchFoodServiceReference.Categorie c) {
            return base.Channel.UpdateCategoriesAsync(c);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Commentaire>> GetCommentairesAsync() {
            return base.Channel.GetCommentairesAsync();
        }
        
        public System.Threading.Tasks.Task<SearchFood.SearchFoodServiceReference.Commentaire> GetCommentaireAsync(int id) {
            return base.Channel.GetCommentaireAsync(id);
        }
        
        public System.Threading.Tasks.Task AddCommentairesAsync(SearchFood.SearchFoodServiceReference.Commentaire c) {
            return base.Channel.AddCommentairesAsync(c);
        }
        
        public System.Threading.Tasks.Task DeleteCommentairesAsync(int id) {
            return base.Channel.DeleteCommentairesAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateCommentairesAsync(SearchFood.SearchFoodServiceReference.Commentaire c) {
            return base.Channel.UpdateCommentairesAsync(c);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Historique>> GetHistoriquesAsync() {
            return base.Channel.GetHistoriquesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Historique>> GetHistoriqueByUserAsync(int idUser) {
            return base.Channel.GetHistoriqueByUserAsync(idUser);
        }
        
        public System.Threading.Tasks.Task AddHistoriqueAsync(SearchFood.SearchFoodServiceReference.Historique h) {
            return base.Channel.AddHistoriqueAsync(h);
        }
        
        public System.Threading.Tasks.Task DeleteHistoriqueAsync(SearchFood.SearchFoodServiceReference.Historique h) {
            return base.Channel.DeleteHistoriqueAsync(h);
        }
        
        public System.Threading.Tasks.Task UpdateHistoriqueAsync(SearchFood.SearchFoodServiceReference.Historique h) {
            return base.Channel.UpdateHistoriqueAsync(h);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Note>> GetNotesAsync() {
            return base.Channel.GetNotesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Note>> GetNoteByRestaurantAsync(int idRestaurant) {
            return base.Channel.GetNoteByRestaurantAsync(idRestaurant);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Note>> GetNoteByUserAsync(int idUser) {
            return base.Channel.GetNoteByUserAsync(idUser);
        }
        
        public System.Threading.Tasks.Task AddNotesAsync(SearchFood.SearchFoodServiceReference.Note n) {
            return base.Channel.AddNotesAsync(n);
        }
        
        public System.Threading.Tasks.Task DeleteNotesAsync(SearchFood.SearchFoodServiceReference.Note n) {
            return base.Channel.DeleteNotesAsync(n);
        }
        
        public System.Threading.Tasks.Task UpdateNotesAsync(SearchFood.SearchFoodServiceReference.Note n) {
            return base.Channel.UpdateNotesAsync(n);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Restaurant>> GetRestaurantsAsync() {
            return base.Channel.GetRestaurantsAsync();
        }
        
        public System.Threading.Tasks.Task<SearchFood.SearchFoodServiceReference.Restaurant> GetRestaurantAsync(int id) {
            return base.Channel.GetRestaurantAsync(id);
        }
        
        public System.Threading.Tasks.Task AddRestaurantsAsync(SearchFood.SearchFoodServiceReference.Restaurant r) {
            return base.Channel.AddRestaurantsAsync(r);
        }
        
        public System.Threading.Tasks.Task DeleteRestaurantsAsync(int id) {
            return base.Channel.DeleteRestaurantsAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateRestaurantsAsync(SearchFood.SearchFoodServiceReference.Restaurant r) {
            return base.Channel.UpdateRestaurantsAsync(r);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Type_Cuisine>> GetTypesCuisineAsync() {
            return base.Channel.GetTypesCuisineAsync();
        }
        
        public System.Threading.Tasks.Task<SearchFood.SearchFoodServiceReference.Type_Cuisine> GetTypeCuisineAsync(int id) {
            return base.Channel.GetTypeCuisineAsync(id);
        }
        
        public System.Threading.Tasks.Task AddTypesCuisineAsync(SearchFood.SearchFoodServiceReference.Type_Cuisine tc) {
            return base.Channel.AddTypesCuisineAsync(tc);
        }
        
        public System.Threading.Tasks.Task DeleteTypesCuisineAsync(int id) {
            return base.Channel.DeleteTypesCuisineAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateTypesCuisineAsync(SearchFood.SearchFoodServiceReference.Type_Cuisine tc) {
            return base.Channel.UpdateTypesCuisineAsync(tc);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<SearchFood.SearchFoodServiceReference.Utilisateur>> GetUtilisateursAsync() {
            return base.Channel.GetUtilisateursAsync();
        }
        
        public System.Threading.Tasks.Task<SearchFood.SearchFoodServiceReference.Utilisateur> GetUtilisateurAsync(int id) {
            return base.Channel.GetUtilisateurAsync(id);
        }
        
        public System.Threading.Tasks.Task AddUtilisateursAsync(SearchFood.SearchFoodServiceReference.Utilisateur u) {
            return base.Channel.AddUtilisateursAsync(u);
        }
        
        public System.Threading.Tasks.Task DeleteUtilisateursAsync(int id) {
            return base.Channel.DeleteUtilisateursAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateUtilisateursAsync(SearchFood.SearchFoodServiceReference.Utilisateur u) {
            return base.Channel.UpdateUtilisateursAsync(u);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISearchFoodService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISearchFoodService)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:24048/SearchFoodService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return SearchFoodServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISearchFoodService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return SearchFoodServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISearchFoodService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_ISearchFoodService,
        }
    }
}
