//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFoodServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.Restaurant = new HashSet<Restaurant>();
        }
    
        public int Id_Categorie { get; set; }
        public string Nom_Categorie { get; set; }
    
        public virtual ICollection<Restaurant> Restaurant { get; set; }
    }
}
