//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFoodServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historique
    {
        public int Id_Historique { get; set; }
        public int Id_Restaurant { get; set; }
        public int Id_Utilisateur { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
