//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFoodServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Cuisine
    {
        public Type_Cuisine()
        {
            this.Restaurant = new HashSet<Restaurant>();
        }
    
        public int Id_Type_Cuisine { get; set; }
        public string Type_Cuisine1 { get; set; }
    
        public virtual ICollection<Restaurant> Restaurant { get; set; }
    }
}
